[package]
name = "simple_link_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.14", features = ["json"] }
scraper = "0.23.1"
tokio = { version = "1.44.1", features = ["full"] }
url = "2.5.4"
